### ISSUE TITLE
“Error while connecting to server” with -ngx

### ISSUE THREAD

**Issue by avidrissman** [bauerj/paperless_app#128]
I’m running the latest Paperless-ngx, 1.15.1, and I have the current App Store version. When I put in my server address I get:

```
Error while connecting to server

DioError [DioErrorType.other]: SocketException:
Connection refused (OS Error: Connection
refused, errno = 61), address = 100.93.180.102,
port = 62835
Source stack:
# DioMixin.fetch (package:dio/src/dio_mixin.dart:473)
#1 DioMixin.request (package:dio/src/dio_mixin.dart:468)
#2 DioMixin.get (package:dio/src/dio_mixin.dart:55)
#3 API.testConnection (package:paperless_app/api.dart:248)
#4 _ServerDetailsRouteState.save (package:paperless_app/routes/server_details_route.dart:45)
<asynchronous suspension>
```

It seems like Paperless and -ng are gone, and -ngx is the new thing. Is that something you’re looking to support?

**Comment by avidrissman** [comment]
I didn't realize that I needed to put a port number in the server address. It works now.
