### ISSUE TITLE
No login to the server possible

### ISSUE THREAD

**Issue by HHZZUUJH** [bauerj/paperless_app#129]
Hello,

YunoHost Version: 11.1.21.4 (stable)
Paperless-ngx for YunoHost version: 1.16.2~ynh2
anzumeldender Nutzer: superuseed
 

Fehler beim Verbinden mit dem Server:

DioError [DioErrorType.response]: Https status error [200]

Source stack:
#0 Dio.Mixin.fetch (package:dio/src/dio_mixin.dart:473)

#1 Dio.Mixin.request (package:dio/src/dio_mixin.dart:468)

#2 Dio.Mixin.get (package:dio/src/dio_mixin.dart:55)

#3 API.checkCredentials (package:paperless_app/api.dart:250) <asychronous suspension>
	
#4 _LoginRouteState.save (package:paperless_app/routes/login_route.dart:44) <asychronous suspension>

Thanks. Best regards

**Comment by Pupo1** [comment]
I have the same problem, but only when I have a space in my password.
