### ISSUE TITLE
Editing documents with paperless-ngx 2.0 fails

### ISSUE THREAD

**Issue by cmusik** [bauerj/paperless_app#137]
**Describe the bug**
Since Paperless-ngx 2.0 editing documents does not work

**To Reproduce**
1. Open document
2. Change something
3. Save

**Expected behavior**
Changes are saved

**Logs**

In the edit request I get the message:

```
{"custom_fields":["Dieses Feld ist erforderlich."]}
```

In the app logs there is this stacktrace:

```
---BEGIN STACKTRACE---
#0      PaperlessDocumentsApiImpl.update (package:paperless_api/src/modules/documents_api/paperless_documents_api_impl.dart:85)
<asynchronous suspension>
#1      DocumentEditCubit.updateDocument (package:paperless_mobile/features/document_edit/cubit/document_edit_cubit.dart:35)
<asynchronous suspension>
#2      _DocumentEditPageState._onSubmit (package:paperless_mobile/features/document_edit/view/document_edit_page.dart:389)
<asynchronous suspension>

---END STACKTRACE---
```

**Additional information**
*Paperless App Version*: 3.1.3
*Do you use Paperless NG as a backend*: Yes

**Comment by cmusik** [comment]
sorry, wrong paperless app
